import type { NextPage } from 'next'
import Head from 'next/head'
import ChatContainer from '../components/ChatContainer'
import ChatSidebar from '../components/ChatSidebar'
// import { trpc } from "../utils/trpc"

const Home: NextPage = () => {
  // const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-row divide-x divide-neutral-700/50">
        <ChatSidebar />

        <ChatContainer />
      </main>
    </>
  )
}

export default Home
